demoapp/urls.py
from django.urls import path
from . import views

app_name = 'demoapp'

urlpatterns = [
    path('', views.base, name="base"),
    path('login', views.login_method, name="login"),
    path('logout', views.logout_method, name="logout"),
    path('register/company', views.company_register, name="company_register"),
    path('register/seeker', views.seeker_register, name="seeker_register"),
    path('company/dashboard', views.company_dash, name = "company_dash"),
    path('seeker/dashboard', views.seeker_dash, name = "seeker_dash"),    
    path('profile/view', views.profile_view, name="profile_view"),
    path('profile/update', views.profile_update, name="profile_update"),
    path('profile/delete', views.profile_delete, name="profile_delete"),
    path('post/read/all/', views.post_read_all, name="post_read_all"),
    path('post/create/', views.post_create, name="post_create"),
    path('post/update/<int:id>', views.post_update, name="post_update"),
    path('post/delete/<int:id>', views.post_delete, name="post_delete"),
    path('cv/read/all', views.cv_read_all, name="cv_read_all"),
    path('cv/create/', views.cv_create, name="cv_create"),
    path('cv/update/<int:id>', views.cv_update, name="cv_update"),
    path('cv/delete/<int:id>', views.cv_delete, name="cv_delete"),
    path('search', views.search, name="search"),
    path('company/detail/<int:c_id>', views.company_detail, name = 'company_detail'),
    path('seeker/detail/<int:s_id>', views.seeker_detail, name = 'seeker_detail'),
    path('post/detail/<int:id>', views.post_detail, name = 'post_detail'),
    path('posts/all', views.all_posts, name="all_posts"),
    path('application/view', views.application_view, name= "application_view"),
    path('application/create/<int:post_id>/<int:company_id>', views.application_create, name = "application_create"),
    path('application/delete/<int:app_id>', views.application_delete, name = 'application_delete'),
    path('application/accept/<int:app_id>', views.accept_application, name = 'accept_application'),
    path('application/cancel/<int:app_id>', views.cancel_application, name = 'cancel_application'),

]

demosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('demoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demoapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.core.exceptions import ValidationError
from django.core import validators
from django.http import request

class User_Creation_Form(UserCreationForm):  # Admin 
    class Meta:
        model = User
        fields = "__all__"    

class User_Form(forms.ModelForm):   
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ("username", "email", "password")
        help_texts = {"username": ""}
        widgets =  {'password': forms.PasswordInput()}  

    def clean_username(self):
        username = self.cleaned_data['username']        
        if User.objects.filter(username = username).exists():
            raise forms.ValidationError("username already exists !!")
        return username

    def clean(self):
        cleaned_data = super(User_Form, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("password and confirm_password does not match"            )
                                                 

class Company_Form(forms.ModelForm):
    class Meta:
        model = Company
        fields = ("cname", "ctype", "estd", "ceo", "phone", "clocation", "logo")
        labels = {"cname": "Company Name", "ctype" : "Company Type", "estd": "Estd.", "ceo": "CEO",
                  "phone" : "contact no.", "clocation": "Company Address", "logo": "logo -"}
        widgets = {
            'estd': forms.TextInput(attrs={'placeholder': '(yyyy)'}),
        }


class Seeker_Form(forms.ModelForm):
    class Meta:
        model = Seeker
        fields = ("name", "sex", "dob" , "nationality", "qualification", "experience" , "phone", "address", "issued_id", "photo")
        labels = {"photo": "photo -",}
        widgets = {
            'issued_id': forms.TextInput(attrs={'placeholder': 'national-identity'}),
            'dob': forms.TextInput(attrs={'placeholder': '(yyyy-mm-dd)'}),
            'sex': forms.TextInput(attrs={'placeholder': 'male/female/other'}),
            'experience': forms.TextInput(attrs={'placeholder': ' in year :'}),            
        }  
    

class Post_Form(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "description", "vacant_for", "no_of_vacancy",)
        labels = {"no_of_vaccancy": "No. of Vaccancy"}


class CV_Form(forms.ModelForm):
    class Meta:
        model = CV
        fields = ("cv",)
        labels = {'cv': ""}

demoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib.auth.models import Group
from django.views.generic import View
from .models import *
from django.utils import timezone
from demosite import settings
from django.contrib import messages
from django.db.models import Q
from itertools import chain
from operator import attrgetter


# Create your views here.


def base(request):
    posts = Post.objects.filter(company__is_verified='True').order_by('-published_date')[:4] 
    company= Company.objects.all()
    total_company = company.count()
    seeker = Seeker.objects.all()
    total_seeker = seeker.count()
    return render(request, 'base.html', {'posts': posts, 'total_company': total_company,'total_seeker': total_seeker})

def all_posts(request):
    posts = Post.objects.filter(company__is_verified='True').order_by('-published_date')[:8]
    company= Company.objects.all()
    total_company = company.count()
    seeker = Seeker.objects.all()
    total_seeker = seeker.count()
    return render(request, 'base.html', {'posts': posts, 'total_company': total_company,'total_seeker': total_seeker})

def login_method(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                u = user.username
                print(u, " : Logged in")                                
                if user.is_company:                    
                    messages.success(request, '* Logged in as a company !!')
                    return HttpResponseRedirect('/company/dashboard')
                if user.is_seeker:                    
                    messages.success(request, "*  Logged in as an Applicant !!")
                    return HttpResponseRedirect('/seeker/dashboard')
                else:
                    messages.success(request, "* Logged in as Admin !!")
                    return HttpResponseRedirect('/')
            else:
                messages.error(request, "User doesn't exist.")
                return HttpResponseRedirect('/login')
        else:
            messages.warning(request, "* INVALID CREDENTIALS !!")
            return HttpResponseRedirect('/login')
    else:
        return render(request, 'login_form.html')


@login_required
def logout_method(request):
    logout(request)
    messages.success(request, "* Successfully Logged out !!")
    return HttpResponseRedirect('/login')


def company_register(request):
    registered = False
    if request.method == 'POST':
        user_form = User_Form(request.POST)
        profile_form = Company_Form(request.POST, request.FILES)        
        if user_form.is_valid() and profile_form.is_valid():            
            user = user_form.save()             
            user.set_password(user.password)
            user.is_company = True
            user.save()
            # Additional fields
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
            messages.success(request, "* Successfully Registered as a Company .......")
            return HttpResponseRedirect('/login')            
        else:
            messages.error(request,"* Invalid data . Try Again !!")
            return HttpResponseRedirect('/register/company')
    else:
        context = {
            'user_form' : User_Form(),
            'profile_form' : Company_Form(), 
            'registered' : registered
        }
    return render(request, 'company_register.html',  context = context)


def seeker_register(request):
    registered = False
    if request.method == 'POST':
        user_form = User_Form(request.POST)
        profile_form = Seeker_Form(request.POST, request.FILES)        
        if user_form.is_valid() and profile_form.is_valid():             
            user = user_form.save()
            user.set_password(user.password)
            user.is_seeker = True
            user.save()
            # Additional fields
            profile = profile_form.save(commit=False)
            # age calculation
            profile.age = (datetime.datetime.now().year - profile.dob.year)
            profile.user = user
            profile.save()
            registered = True
            messages.success(request, "* Successfully Registered as an Applicant .......")
            return HttpResponseRedirect('/login')
        else:
            messages.error(request,"* Invalid data . Try Again !!")
            return HttpResponseRedirect('/register/seeker')
    else:
        context = {
            'user_form' : User_Form(),
            'profile_form' : Seeker_Form(),
            'registered' : registered 
        }        
    return render(request, 'seeker_register.html', context = context)

# DashBoard

@login_required(login_url='/login')
def company_dash(request):
    if request.user.is_company:
        return render(request, 'company_dash.html')

@login_required(login_url='/login')
def seeker_dash(request):
    if request.user.is_seeker:
        return render(request, 'seeker_dash.html')

# Profile CRUD

@login_required(login_url='/login')
def profile_view(request):
    if request.user.is_company:
        company = Company.objects.get(user=request.user)
        return render(request, 'company_profile.html', {'company': company})
    elif request.user.is_seeker:
        seeker = Seeker.objects.get(user=request.user)            
        return render(request, 'seeker_profile.html', {'seeker': seeker})
    else:
        messages.error(request,"* U r not authenticated !!")  
        return HttpResponseRedirect('/')  


@login_required(login_url='/login')
def profile_update(request):
    if request.user.is_company:
        company = Company.objects.get(user = request.user)
        company_profile = Company_Form(instance = company)
        a_company = True
        if request.method == "POST":
            data = Company_Form(request.POST, request.FILES, instance = company)
            if data.is_valid():
                data.save(commit = True)
                messages.success(request, "* Profile Updated successfully .....")
                return HttpResponseRedirect('/profile/view')
            else:
                messages.error(request,"* Invalid data . Try Again !!")
                return HttpResponseRedirect('/profile/update')   
        context = {
            'company_profile':company_profile,
            'a_company': a_company
        }
        return render(request, 'profile_update.html', context = context)

    elif request.user.is_seeker:
        seeker = Seeker.objects.get(user = request.user)
        seeker_profile = Seeker_Form(instance = seeker)
        a_seeker = True
        if request.method == "POST":
            data = Seeker_Form(request.POST, request.FILES, instance = seeker)
            if data.is_valid():
                data.save(commit = True)       
                messages.success(request, "* Profile Updated successfully !!")        
                return HttpResponseRedirect('/profile/view')
            else:
                messages.error(request,"* Invalid data . Try Again !!")
                return HttpResponseRedirect('/profile/update')
        context = {
            'seeker_profile': seeker_profile, 
            'a_seeker': a_seeker
        }
        return render(request, 'profile_update.html', context = context)
        
    else:
        messages.error(request, "you are not Authenticated !!")
        return HttpResponseRedirect('/')


@login_required(login_url='/login')
def profile_delete(request):
    if request.method == "GET":
        if request.user.is_company:
            user = User.objects.get(username = request.user)
            company = Company.objects.get(user = user)
            posts = Post.objects.filter(company = company)
            logout(request)  
            user.delete()
            posts.delete()
            company.delete()    
            messages.success(request, "your account was successfully deleted .")
            return HttpResponseRedirect('/')   

        elif request.user.is_seeker:
            user = User.objects.get(username = request.user)
            seeker = Seeker.objects.get(user = request.user)
            cv = CV.objects.filter(seeker = seeker)
            logout(request)
            user.delete()
            cv.delete()
            seeker.delete()
            messages.success(request, "your account was successfully deleted .")
            return HttpResponseRedirect('/')
            
        else:
            messages.error(request, "you are not Eligible .")
            return HttpResponseRedirect('/')

# POST CRUD

@login_required(login_url='/login')
def post_read_all(request):
    if request.method == "GET":
        if request.user.is_company:
            company = Company.objects.get(user=request.user)
            post = Post.objects.filter(company=company).order_by('-published_date')                    
            return render(request, 'post_view_all.html', {'post': post, 'company': company})
        else:
            messages.error(request, "* You are not authenticated !!")
            return HttpResponseRedirect('/')

@login_required(login_url='/login')
def post_create(request):
    form = Post_Form()
    company = Company.objects.get(user=request.user)
    new_post = True
    if not company.is_verified:
        messages.warning(request,"* You are not verified yet !! ")
        return HttpResponseRedirect('/company/dashboard')
    else:
        if request.method == "POST":
            data = Post_Form(data=request.POST)

demoapp/templates/company_dash.html
{% extends 'parent.html' %}
{% load static %}

    {% block content %}
        <div class="container jumbotron" style="position: relative;  background: linear-gradient(to left, rgba(25, 44, 7, 0), rgba(53, 226, 197, 0.966), rgba(25, 44, 7, 0)); border-radius: 10px;">
            <div class="jumbotron shadow" style="background: linear-gradient(to left, rgba(25, 44, 7, 0),rgba(255, 255, 255, 0.966),rgba(25, 44, 7, 0)); border-radius: 16px;">
                <center>
                    <a class="btn btn-success" href="{% url 'demoapp:profile_view' %}">Profile</a>  
                    <a class="btn btn-warning" href="{% url 'demoapp:post_read_all' %}">Posts</a>
                    <a class="btn btn-primary" href="{% url 'demoapp:application_view' %}">Applications</a>
                </center>
            </div>
        </div>        
    {% endblock %}

demoapp/templates/company_profile.html
{% extends 'parent.html' %}
{% load static %}

{% block content %}
    <center>

        <style>
            .card {              
                background-image: linear-gradient(to left, rgba(131, 204, 58, 0.062), rgb(35, 214, 146));           
            }
            .btn-danger {
                background-image: linear-gradient(to left, rgba(161, 216, 110, 0), rgb(31, 231, 57));
            }
            #s-profile{
                float: left;
                font-family: 'Times New Roman', Times, serif;
                color: black;
                margin-left: 8px;

            }
            .card-title{
                font-family: Verdana, Geneva, Tahoma, sans-serif;
                color: black;
            }
            .s-item{
                float: left;
                font-family: sans-serif;
                font-weight: 100;
                color: rgba(0, 0, 0, 0.788);   
                margin-left: 14px;   
                line-break: auto; 
            }
            .card-body{
                height: auto;
                width: auto;
                box-shadow: 100px;
                stroke-opacity: initial;
            }
            #verified{
                float: left;
                margin-left: 6px;
                color: rgb(21, 42, 231);
                padding: 4px;
            }   
            #jumbo{
                background-image: linear-gradient(to left, rgba(131, 204, 58, 0.062), rgb(35, 214, 146), rgba(131, 204, 58, 0.062));              
                height: auto;
                width: auto;			
                text-align: center;						
                margin:auto;
                margin-top: 0%;
                margin-bottom: auto;
                margin-left: auto;
                margin-right: auto;	
                padding: auto;
                padding-top: auto;
                padding-bottom: auto;
                padding-left: auto;
                padding-right: auto;		
                aspect-ratio: auto;
                align-items: center;
                align-self: center;	    
                letter-spacing: 1px;            	    
            }       
            
        </style>
        <div class="container jumbotron" id="jumbo">
        <div class="card shadow" style="text-align: center;">                       
            <div class="row no-gutters">                                             
                <div class="col-sm-4">         
                    {% if company.logo %}
                        <div class="shadow h-100 w-100">
                            <img class = "img-responsive rounded-circle" src="{{ company.logo.url }}" height="200" width="200"><br>
                            <h5 class="card-title" style="font-family: cursive; font-weight: 100; background-color: rgb(233, 23, 23); color: white; margin-top: 6px;">{{company.cname}}</h5>                            
                        </div>
                    {% else %}
                        <div class="shadow h-100 w-100">
                            <img class="rounded-circle" src="{% static 'assets\img\company-demo.png' %}" class="rounded-circle img m-2 p-2" height="200"  width="200">
                            <h5 class="card-title" style="font-family: cursive; font-weight: 100; background-color: rgb(233, 23, 23); color: white; margin-top: 6px;">{{company.cname}}</h5>
                        </div>
                    {% endif %}    
                </div>

                <div class="col-sm-7">
                    <div class="card-body"> 
                        <h5 class="card-title"><b > Profile </b></h5> <hr>     
                        <b id="s-profile">Type : </b> <span class="s-item">  {{company.ctype}}  </span> <br>
                        <b id="s-profile">CEO : </b> <span class="s-item">  {{company.ceo}}  </span> <br>
                        <b id="s-profile">Location : </b> <span class="s-item">  {{company.clocation}}  </span> <br>
                        <b id="s-profile">Established : </b> <span class="s-item">  {{company.estd}}  </span> <br>
                        <b id="s-profile">email : </b> <span class="s-item">  {{company.user.email}}  </span> <br> 
                        <b id="s-profile">phone : </b> <span class="s-item">  {{company.phone}}  </span> <br>                        
                                              
                        {% if company.is_verified %}
                            <b id="s-profile">Verified : </b>
                            <i class="icofont-check fa-lg" id="verified"></i>
                        {% else %}
                            <b id="s-profile">Verified : </b>
                            <span class="s-item" style="color: rgb(255, 0, 106); font-size: medium;"> <i>Not Yet</i></span>
                        {% endif %} <br> <br>

                        {% if not detail %}                            
                            <div class="m-2 p-0">
                                <a class="btn btn-success btn-sm" href="{% url 'demoapp:profile_update' %}">update</a>
                                <a class="btn btn-outline-danger btn-sm" href="{% url 'demoapp:profile_delete' %}">remove account</a>
                            </div>
                        {% else %}        
                            <center>
                                <a class="btn btn-sm btn-success" href="{% url 'demoapp:post_detail' company.id %}">view Posts</a>
                            </center>
                        {% endif %}                                          
                    </div>
                </div>
            </div>
        </div>
        </div>
    </center>
{% endblock %}

demoapp/templates/parent.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>work - overflow</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <script src="https://kit.fontawesome.com/834d2663f4.js" crossorigin="anonymous"></script>

  <!-- Favicons -->
  <link class="site-logo" rel="shortcut icon" href="{% static 'assets/img/web-logo-removebg-preview.png' %}">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link
   rel="stylesheet"
   href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
   integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
   crossorigin="anonymous"
  />
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Moderna - v2.2.1
  * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="rounded" style="background-image:
  url('https://png.pngtree.com/thumb_back/fw800/back_our/20190623/ourmid/pngtree-corporate-conference-international-image_238920.jpg'); 
  height: auto; width: auto;"
>
  <style>
    .form-control{
      background: url("http://kodyrabatowe.wp.pl/img/ico/search_gr.png") top left no-repeat;
      border-radius: 8px;
      border-width: 1.4px;
      height:35px;
      padding-left:12px;
      border-color: aqua;
      border-right-width: 1.4px; 
      color: white;     
    }
    
    .btn-outline-info{   
      margin-left: 2px;
      margin-block-end: 6px;
      padding-left: 10px;
      padding-right: 10px;
      box-sizing: border-box;    
      border-radius: 9px;
      height: 35px;
      border-width: 1.4px;
      border-left-width: 0px;
      border-color: aqua;
      color: rgba(255, 255, 255, 0.856);
    }

    .btn-outline-info:hover {
      border: none;
      height: 35px;
      border-width: 1.4px;
      background-image: linear-gradient(to left, rgba(248, 244, 244, 0), rgb(126, 231, 217));
    }

    .dp{
      margin-left:40px;
      margin-right: -50px; 
    }

    #dpimg{
      position: absolute;
      margin: -8px;
    }
    .btn-success {
      background-image: linear-gradient(to left, rgba(161, 216, 110, 0), rgb(31, 231, 57));
    }
    .btn-primary {
      background-image: linear-gradient(to right, rgba(161, 216, 110, 0), rgb(30, 14, 243));
    }
    .btn-warning {
      background-image: linear-gradient(to left, rgb(255, 9, 9), rgba(248, 244, 244, 0), rgb(255, 9, 9));
      color: black;
    }
    .btn-warning:hover{
      background-color: yellow;
      color: whitesmoke;
    }
    .btn-danger {
      background-color: red;  
    }
    .btn-danger:hover{
      background-image: linear-gradient(to right, rgba(225, 230, 220, 0), rgb(253, 0, 0));  
    }
    

  </style> 
    

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container">
      <div class="logo float-left">
        <h1 class="text-light"><a href="{% url 'demoapp:base' %}"><span>WORK OVERFLOW</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
      </div>

      <!--  nav  -->
      <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="base"><a href="{% url 'demoapp:base' %}">Home</a></li>
          <li class="drop-down"><a href="#">Register</a>
                <ul>
                  <li><a href="{% url 'demoapp:company_register' %}"><b>a company</b></a></li>
                  <li><a href="{% url 'demoapp:seeker_register' %}"><b>job seeker</b></a></li>
                </ul>
          </li>
          {% if user.is_authenticated %}
            {% if user.is_company %}
                <li><a href="{% url 'demoapp:company_dash' %}">DashBoard</a></li>
            {% elif user.is_seeker %}
                <li><a href="{% url 'demoapp:seeker_dash' %}">DashBoard</a></li>
            {% endif %}
            <li><a href="{% url 'demoapp:logout' %}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'demoapp:login' %}">Login</a></li>
          {% endif %}

          <li>
            <form action="{% url 'demoapp:search' %}" method="GET">
                <div class="input-group mb-3">                
                    <input type="search" class="form-control" id="sb" name="job_request" placeholder=" company/job/location" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-outline-info" type="submit"><i class="fas fa-search"></i></button>
                        </div>            
                </div>
            </form>
          </li>
          
          {% if user.is_authenticated %}
            <li><a href="{% url 'demoapp:profile_view' %}" class="dp"><img class="rounded-circle" src="https://unoreads.com/user_profile_pic/demo-user.png" id="dpimg" height="30" width="30" alt="logo"></a></li>           
          {% endif %}
        </ul>
      </nav>
      <!--  END Nav  -->

    </div>
  </header> <br>
  <!-- End Header --> 

    

  <!-- ======= main-item ======= -->   
  <main id="main">  

  <!--  django msg  -->
  {% if messages %}
    {% for message in messages %}
      <div class="alert {{ message.tags }} m-3 p-1" id="msg" roles="alert">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  <!-- msg end -->

    <section data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
        
      {% block content %}
        
          
      {% endblock %}
      
    </section>    
  </main>
  <!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">

    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              Bhubaneswar Central <br>
              751014 , 
              Odisha<br>
              India <br> <br>
              <strong>Phone:</strong> +91 xxxxxxxxxx<br>
              <strong>Email:</strong> dashbabu@gmail.com<br>
            </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-info">
            <h3>About Us</h3>
            <p>We are trying to provide you a <br>
                better and powerful Work-Your-Own platform <br>
                where you can get your job done <br>     
                at just One-Click .</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>    

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span> work - overFlow </span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/ -->
        Designed by <a href="https://instagram.com/dashgirija_edge"><i> " <u>dash babu</u> " </i> </a> with L O V E
      </div>
    </div>
  </footer>
  

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script>
    var message_ele = document.getElementById("msg");
    setTimeout(function(){ 
      message_ele.style.display = "none"; 
    }, 5000);   
  </script>  

</body>
</html>